### ISSUE TITLE
A lot of files are missing

### ISSUE THREAD

**Issue by YazhouTUD** [sravi-uwmadison/Exp_design_sparse#2]
This code cannot work since many files are missing. For example, we cannot run "lin_reg_example.m", since we miss "processed_lin_reg.txt", "d_opt.m" and "pipage.m".

**Comment by YazhouTUD** [comment]
we also need the "roisummaries.mat'" data.

**Comment by sravi-uwmadison** [comment]
Thanks for pointing these out, I've added d_opt.m but it really isn't needed for our algorithm. "pipage.m" is a standard algorithm as mentioned in our paper, if your data is good, you don't really need this as well, just rounding worked for our purposes. "processed_lin_reg.txt" , "roisummaries.dat" are just data files. I'll try to add these as soon as possible.
